<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishAot>true</PublishAot>
    <SelfContained>true</SelfContained>
    <InvariantGlobalization>true</InvariantGlobalization>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>VRCNeph</AssemblyName>
    <ApplicationIcon>..\Source Code\src\App\VRCNeph.ico</ApplicationIcon>
    <Version>1.0.35</Version>
    <AssemblyVersion>$(Version).0</AssemblyVersion>
    <FileVersion>$(Version).0</FileVersion>
    <InformationalVersion>$(Version)</InformationalVersion>
    <IsTrimmable>true</IsTrimmable>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\artifacts\release\VRCNephAssets.zip" LogicalName="VRCNephAssets.zip" />
  </ItemGroup>
</Project>
